### ISSUE TITLE
Upstreaming your decoder

### ISSUE THREAD

**Issue by abraxa** [Knio/pulseview_ir_sirc#1]
Hi, would you consider upstreaming your PD so it can be included in the collection of official PDs?

https://sigrok.org/wiki/Protocol_decoder_HOWTO#Submitting_your_decoder

**Comment by Knio** [comment]
I have had https://github.com/sigrokproject/libsigrokdecode/pull/29 open for a while now and nobody seems interested yet. If you have some connections feel free to poke someone.

**Comment by abraxa** [comment]
Ah thanks, I didn't see you had opened a PR. Even better then :)

I'll see to it being merged.

**Comment by abraxa** [comment]
Do you have some sample .sr files that can be added to https://github.com/sigrokproject/sigrok-dumps ?

**Comment by Knio** [comment]
Merged!
